export const metadata = {
  title: "Home - Kevin Lane",
  description: "Generated by create next app",
};

import RootLayoutClient from './root-layout-client';

export default function RootLayout({ children }) {

return (
    <RootLayoutClient>
      {children}
    </RootLayoutClient>
  );
}
